### ISSUE TITLE
Support for rhythmbox 3.4.3

### ISSUE THREAD

**Issue by daniel88ferreira** [fossfreedom/alternative-toolbar#136]
Hi,
I've just updated rhythmbox in my arch linux installation to 3.4.3-1 and the plugin doesn't work as expected, see screenshot:
![image](https://user-images.githubusercontent.com/23555804/50786468-94ffa400-12ab-11e9-8715-291ff74d0b9a.png)
Also I've started it from the command line and it shows:
~~~
$ rhythmbox -D alternative
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alternative-toolbar.py", line 174, in do_activate
    self.toolbar_type.initialise(self)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 1330, in initialise
    self._setup_playbar()
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 1391, in _setup_playbar
    action.set_active(True)
AttributeError: 'NoneType' object has no attribute 'set_active'
(18:35:46) [0x559960ac5b90] [AltToolbarHeaderBar.reset_categories_pos] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:528: reset categories position
(18:35:46) [0x559960ac5b90] [AltToolbarHeaderBar.reset_categories_pos] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:538: not horizontal
(18:35:46) [0x559960ac5b90] [AltToolbarHeaderBar.reset_toolbar] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:3187: <__gi__.RBLibrarySource object at 0x7fa877a45168 (RBLibrarySource at 0x559960b98860)>
(18:35:46) [0x559960ac5b90] [AltToolbarHeaderBar.reset_toolbar] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:1044: reset toolbar
(18:35:46) [0x559960ac5b90] [AltToolbarHeaderBar.reset_toolbar] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:1052: found
(18:35:46) [0x559960ac5b90] [AltToolbarHeaderBar.library_radiobutton_toggled] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:2855: library_radiobutton_toggled
(18:35:46) [0x559960ac5b90] [AltMusicLibraryController.update_controls] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:389: browser view found
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 160, in delayed
    self.on_startup()
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 1353, in on_startup
    super(AltToolbarHeaderBar, self).on_startup(*args)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 781, in on_startup
    super(AltToolbarShared, self).on_startup(*args)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 193, in on_startup
    self.reset_toolbar(self.shell.props.selected_page)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 1598, in reset_toolbar
    self._set_toolbar_controller()
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 1620, in _set_toolbar_controller
    current_controller.update_controls(self.shell.props.selected_page)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py", line 202, in update_controls
    self.header.set_library_box_sensitive(True)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 1631, in set_library_box_sensitive
    self.library_box.set_sensitive(sensitive)
AttributeError: 'AltToolbarHeaderBar' object has no attribute 'library_box'
~~~

Versions:
~~~
$ yaourt -Qs rhythmbox
extra/rhythmbox 3.4.3-1
    Music playback and management application
local/rhythmbox-equalizer 17.10.11.6e706193-1
    10 band graphical equalizer for Rhythmbox
local/rhythmbox-plugin-alternative-toolbar-git 0.r372.75a83b0-1
    Replace the Rhythmbox large toolbar with a Client-Side Decorated or Compact Toolbar which can be hidden
~~~
~~~
System: Arch Linux, x86_64 Linux 4.20.0-arch1-1-ARCH, GNOME Shell 3.30.2 on Xorg
~~~

Hope it helps to find the bug :)

PS: with rhythmbox 3.4.2 it works fine.

Br,
Daniel

**Comment by fossfreedom** [comment]
Daniel,

  ubuntu doesnt carry 3.4.3 just yet so I cannot test this suggestion

https://github.com/fossfreedom/alternative-toolbar/blob/master/alttoolbar_type.py#L1391

Please can you change this to read

```
if action:
   action.set_active(True)
```

Does that work?

**Comment by daniel88ferreira** [comment]
Hi,

I've done that. Top bar is good now, but side bar is blank, also I've chose the dark theme, but it's not being enabled:
![image](https://user-images.githubusercontent.com/23555804/50793299-a5ba1500-12bf-11e9-8d67-b7d347683105.png)

my settings:
![selection_011](https://user-images.githubusercontent.com/23555804/50793697-e6fef480-12c0-11e9-8e81-9f2b67516247.jpg)

the error:
~~~
$ rhythmbox -D alternative
(21:12:49) [0x55fd234df8c0] [AltStandardOnlineController.valid_source] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:1356: NoneType
(21:12:49) [0x55fd234df8c0] [AltStandardLocalController.valid_source] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:1410: NoneType
(21:12:49) [0x55fd234df8c0] [AltErrorsController.valid_source] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:1011: NoneType
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar._setup_headerbar] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:3076: not hidden
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.source_toolbar_visibility] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:1136: source_bar_visibility
(21:12:49) [0x55fd234df8c0] [AltToolbarPlugin.on_page_change] /usr/lib/rhythmbox/plugins/alternative-toolbar/alternative-toolbar.py:836: page changed
(21:12:49) [0x55fd234df8c0] [AltToolbarPlugin.on_page_change] /usr/lib/rhythmbox/plugins/alternative-toolbar/alternative-toolbar.py:836:  
(21:12:49) [0x55fd234df8c0] [AltToolbarPlugin.on_page_change] /usr/lib/rhythmbox/plugins/alternative-toolbar/alternative-toolbar.py:836: None
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.reset_categories_pos] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:528: reset categories position
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.reset_categories_pos] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:530: no page
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.reset_toolbar] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:3189: None
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.reset_toolbar] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:1044: reset toolbar
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.reset_toolbar] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:1046: no page
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.library_radiobutton_toggled] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:2857: library_radiobutton_toggled
(21:12:49) [0x55fd234df8c0] [AltStandardOnlineController.valid_source] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:1356: NoneType
(21:12:49) [0x55fd234df8c0] [AltStandardLocalController.valid_source] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:1410: NoneType
(21:12:49) [0x55fd234df8c0] [AltErrorsController.valid_source] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:1011: NoneType
(21:12:49) [0x55fd234df8c0] [AltGenericController.update_controls] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:386: no browser view
(21:12:49) [0x55fd234df8c0] [AltGenericController.get_toolbar] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:325: None
(21:12:49) [0x55fd234df8c0] [AltGenericController.get_toolbar] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:326: None
(21:12:49) [0x55fd234df8c0] [AltGenericController.update_controls] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:398: no toolbar so nothing left to do - cleanup endbox and exit
(21:12:49) [0x55fd234df8c0] [AltStandardOnlineController.valid_source] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:1356: NoneType
(21:12:49) [0x55fd234df8c0] [AltStandardLocalController.valid_source] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:1410: NoneType
(21:12:49) [0x55fd234df8c0] [AltErrorsController.valid_source] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:1011: NoneType
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.reset_entryview] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:600: reset entryview
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.reset_entryview] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:602: no page

(rhythmbox:9160): Gtk-WARNING **: 21:12:49.411: actionhelper: action app.play-repeat can't be activated due to parameter type mismatch (parameter type b, target type NULL)
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.post_initialise] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:1466: True

(rhythmbox:9160): Gtk-WARNING **: 21:12:49.412: actionhelper: action app.play-shuffle can't be activated due to parameter type mismatch (parameter type b, target type NULL)
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.post_initialise] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:1466: True
(21:12:49) [0x55fd234df8c0] [Repeat._on_repeat_type_changed] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_repeat.py:217: repeat type changed
(21:12:49) [0x55fd234df8c0] [Repeat._on_repeat_type_changed] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_repeat.py:217:  
(21:12:49) [0x55fd234df8c0] [Repeat._on_repeat_type_changed] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_repeat.py:217: False
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.reset_categories_pos] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:528: reset categories position
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.reset_categories_pos] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:538: not horizontal
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.reset_toolbar] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:3189: <__gi__.RBLibrarySource object at 0x7f58a42dcab0 (RBLibrarySource at 0x55fd23752850)>
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.reset_toolbar] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:1044: reset toolbar
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.reset_toolbar] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:1052: found
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.library_radiobutton_toggled] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:2857: library_radiobutton_toggled
(21:12:49) [0x55fd234df8c0] [AltMusicLibraryController.update_controls] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:389: browser view found
(21:12:49) [0x55fd234df8c0] [AltMusicLibraryController.get_toolbar] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:325: <RB.SourceToolbar object at 0x7f58a42e8900 (RBSourceToolbar at 0x55fd23abe590)>
(21:12:49) [0x55fd234df8c0] [AltMusicLibraryController.get_toolbar] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:326: <__gi__.RBLibrarySource object at 0x7f58a42dcab0 (RBLibrarySource at 0x55fd23752850)>
(21:12:49) [0x55fd234df8c0] [AltMusicLibraryController.update_controls] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:407: first time around
(21:12:49) [0x55fd234df8c0] [AltMusicLibraryController.update_controls] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:412: <RB.SourceToolbar object at 0x7f58a42e8900 (RBSourceToolbar at 0x55fd23abe590)>
(21:12:49) [0x55fd234df8c0] [AltMusicLibraryController.get_search_entry] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:349: <Gtk.Entry object at 0x7f58a42e4ab0 (GtkEntry at 0x55fd23a785c0)>
(21:12:49) [0x55fd234df8c0] [AltMusicLibraryController.update_controls] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:428: [<Gtk.Notebook object at 0x7f58a42e8af8 (GtkNotebook at 0x55fd239df3b0)>]
(21:12:49) [0x55fd234df8c0] [AltMusicLibraryController.update_controls] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_controller.py:468: {'searchbar': <Gtk.SearchBar object at 0x7f58a42e8a20 (GtkSearchBar at 0x55fd24510750)>, 'search_button': <Gtk.ToggleButton object at 0x7f58a42e8b88 (GtkToggleButton at 0x55fd246b9290)>}
(21:12:49) [0x55fd234df8c0] [AltToolbarHeaderBar.reset_entryview] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py:600: reset entryview
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 160, in delayed
    self.on_startup()
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 1353, in on_startup
    super(AltToolbarHeaderBar, self).on_startup(*args)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 781, in on_startup
    super(AltToolbarShared, self).on_startup(*args)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 194, in on_startup
    self.reset_entryview(self.shell.props.selected_page)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 318, in reset_entryview
    treeview = entryview.get_child()
AttributeError: 'EntryView' object has no attribute 'get_child'
~~~

1 out of 3 problems seem fixed :)

**Comment by fossfreedom** [comment]
ok - initial fix with this commit https://github.com/fossfreedom/alternative-toolbar/commit/7103702eff369fc29322a43396cde40c597ba7e9

Needs more work here to re-enable the ability to change column positions for each source.

**Comment by fossfreedom** [comment]
BTW - the gtk dark switch is deprecated - GNOME devs now say to use a dark-theme rather than depend on that key.

**Comment by fossfreedom** [comment]
ok - with this commit https://github.com/fossfreedom/alternative-toolbar/commit/8340837c987a96642fdce9ab4da2d8c32e474259 think the column movement capability now works.

v3.4.3 of rhythmbox with the plugin needs a good test since the huge number of commits hides the extensive internal reworking of the GUI - this may impact the plugin further (hopefully not!)

**Comment by daniel88ferreira** [comment]
Thanks, I will test it later today.

**Comment by daniel88ferreira** [comment]
Great! :)
