### ISSUE TITLE
not working on arch linux with kde

### ISSUE THREAD

**Issue by ahmed-h-ayyad** [fossfreedom/alternative-toolbar#143]
when I run rhythmbox from terminal it gives this error 
```
(process:18856): Gtk-WARNING **: 02:49:26.093: Locale not supported by C library.
        Using the fallback 'C' locale.
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alternative-toolbar.py", line 114, in do_activate
    cl.switch_locale(cl.Locale.LOCALE_DOMAIN)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_preferences.py", line 151, in switch_locale
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

```

**Comment by fossfreedom** [comment]
I neither use arch nor kde so cannot help with your setup.

The error means that you dont have the Gtk locale stuff installed correctly.

Best ask on a kde arch forum how to run gtk apps.
