### ISSUE TITLE
Alternative toolbar plugin is not working on arch linux

### ISSUE THREAD

**Issue by pnplusplus** [fossfreedom/alternative-toolbar#174]
I'm using Rhythmbox 3.4.5 and rhythmbox-plugin-alternative-toolbar-git from AUR with yay. 

Here is the log when i open the app.
```
Gtk-WARNING **: 17:05:48.304: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 17:05:48.508: Failed to load module "colorreload-gtk-module"
Gtk-Message: 17:05:48.509: Failed to load module "window-decorations-gtk-module"
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alternative-toolbar.py", line 115, in do_activate
    cl.switch_locale(cl.Locale.LOCALE_DOMAIN)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_preferences.py", line 152, in switch_locale
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.10/locale.py", line 620, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

Here is the log when i unchecked the alternative toolbar plugin
```
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alternative-toolbar.py", line 528, in do_deactivate
    self.rb_toolbar.set_visible(True)
AttributeError: 'AltToolbarPlugin' object has no attribute 'rb_toolbar'. Did you mean: 'get_toolbar'?
```

Here is the log when i checked back the alternative toolbar plugin
```
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alternative-toolbar.py", line 115, in do_activate
    cl.switch_locale(cl.Locale.LOCALE_DOMAIN)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_preferences.py", line 152, in switch_locale
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.10/locale.py", line 620, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

Here is the log when i try to open preferences button
```
(17:06:34) <rhythmbox> [Preferences.do_create_configure_widget] /usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_preferences.py:434: DEBUG - create_display_contents
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_preferences.py", line 224, in do_create_configure_widget
    cl.switch_locale(cl.Locale.LOCALE_DOMAIN)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_preferences.py", line 152, in switch_locale
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.10/locale.py", line 620, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

(rhythmbox:8562): libpeas-gtk-CRITICAL **: 17:06:34.043: show_configure_cb: assertion 'GTK_IS_WIDGET (conf_widget)' failed
```

Any solution?

**Comment by fossfreedom** [comment]
Same issue as this https://github.com/fossfreedom/alternative-toolbar/issues/143

you need to ensure your Gtk locale stuff is working correctly - i.e. environment variables etc.

**Comment by pnplusplus** [comment]
Thanks, now fixed by using this command
`export LC_ALL=C`
