### ISSUE TITLE
Program freezes in terminal error

### ISSUE THREAD

**Issue by witmak38** [fossfreedom/alternative-toolbar#180]
```
(rhythmbox:2268751): Gtk-WARNING **: 22:58:14.395: actionhelper: action app.play-shuffle can't be activated due to parameter type mismatch (parameter type NULL, target type b)
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_rb3compat.py", line 807, in _activate
    self._connect_func(action, None, self._connect_args)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alternative-toolbar.py", line 422, in on_skip_forward
    seek_time = sp.get_playing_time()[1] + seek_forward_time
gi.repository.GLib.Error: rb_shell_player_error: Playback position not available (4)
^[[A^C

```

**Comment by fossfreedom** [comment]
What were you doing to at this time? scrobbling forward?  Repeating one track or repeating a playlist?

What version of rhythmbox are you using and what distro?

**Comment by witmak38** [comment]
Sometimes when flipping through tracks, this happens or by itself over time. operating system: Elementory OS

**Comment by witmak38** [comment]
rhythmbox 3.4.4

**Comment by fossfreedom** [comment]
probably needs a bit of defensive coding around line 422 alternative-toolbar.py to escape from any errors rather than probably looping or whatever is causing the freeze.

**Comment by witmak38** [comment]
could you please tell me how to do it. I am not familiar with python
