### ISSUE TITLE
AttributeError: 'RBAudioscrobblerProfilePage' object has no attribute 'get_entry_view'

### ISSUE THREAD

**Issue by vrishab** [fossfreedom/alternative-toolbar#95]
```
(rhythmbox:30307): Gtk-WARNING **: Allocating size to RBLibraryBrowser 0x7f8c7400e830 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(rhythmbox:30307): Gtk-WARNING **: Allocating size to RBPropertyView 0x18e0f60 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alternative-toolbar.py", line 426, in on_page_change
    self.toolbar_type.reset_entryview(page)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 310, in reset_entryview
    entryview = page.get_entry_view()
AttributeError: 'RBAudioscrobblerProfilePage' object has no attribute 'get_entry_view'
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alternative-toolbar.py", line 426, in on_page_change
    self.toolbar_type.reset_entryview(page)
  File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_type.py", line 310, in reset_entryview
    entryview = page.get_entry_view()
AttributeError: 'RBAudioscrobblerProfilePage' object has no attribute 'get_entry_view'
```

Not sure how to reproduce this issue. All I was doing was normal playback and adding / removing playlists.
##

**Comment by fossfreedom** [comment]
No material issue here.  Code just needs a bit of tidying first to check if an entry view is present before attempting to use the object
