### ISSUE TITLE
Support for Rhythmbox 3.4

### ISSUE THREAD

**Issue by daltones** [fossfreedom/alternative-toolbar#97]
Plugin is broken with brand new Rhythmbox 3.4.
(I'm using `rhythmbox-plugin-alternative-toolbar-git` from AUR, updated today).

Other than that, great job! Thanks for this plugin!

**Comment by veluria** [comment]
Stack trace:

    Traceback (most recent call last):
      File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alternative-toolbar.py", line 151, in do_activate
        self._add_menu_options()
      File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alternative-toolbar.py", line 223, in _add_menu_options
        "Seek backward, in current "
      File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alttoolbar_rb3compat.py", line 545, in add_action
        None)
    TypeError: Argument 3 does not allow None as a value
    Traceback (most recent call last):
      File "/usr/lib/rhythmbox/plugins/alternative-toolbar/alternative-toolbar.py", line 505, in do_deactivate
        self.toolbar_type.cleanup()
    AttributeError: 'AltToolbarPlugin' object has no attribute 'toolbar_type'

**Comment by ahloiscreamo** [comment]
I got affected by this issues too, also installed via git (fedora 24).I hope fix is coming, thanks

**Comment by AshleighAdams** [comment]
I just commented out lines 543–545 in `alttoolbar_rb3compat.py`, then it works fine.

**Comment by fossfreedom** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=770262

This problem is due to upstream issues

**Comment by fossfreedom** [comment]
The above commit should resolve this.
